### PR TITLE
Optional logging for AIMDLimit

### PR DESCRIPTION
**Pull request by IgorPerikov**
**WHAT:** 
Enable logging for limit updates when builder configured with `.enableLogging()`, disabled by default (no breaking change)

**Motivation:**
In a current state `AIMDLimit` suffers from lesser observability, the only way to figure out current limit is via `toString()`, if one wants to track the changes of his limit, he has to execute this method every `N` seconds. 

Drawbacks for this solution are: 1) Inconvenience + extra code 2) You either choose very low `N` or you don't really see the exact transitions (did it dropped once and then stopped growing up or it was constantly dropping and growing back?)

I understand that it might log on every sample, which, depending on the actual rps, might turns out to be a huge amount of messages, although one should enable it both at limit creation stage and log level. That's why I propose it in a `disabled by default` manner. 

Since single queries can mess up the limit it seems very convenient for me to wrap `AIMDLimit` inside `WindowedLimit` and I think this is the case where logging for `AIMDLimit` shines at it's best, because the limit changes are less frequent depending on the window size.

### CODE REVIEW

**Comment by platinummonkey** [comment]
Would this be better suited for adding a listener with your own custom rate-limited logging logic?

**Comment by IgorPerikov** [comment]
> Would this be better suited for adding a listener with your own custom rate-limited logging logic?

Yes, @platinummonkey , it totally makes sense, I missed that part of the library, because it is not accessible on construction phase :sweat_smile: However, listener consumes newLimit only, though current limit is accessible at that point of time as well - https://github.com/Netflix/concurrency-limits/blob/master/concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/AbstractLimit.java#L46

@elandau what do you think about extending notify listeners from `Consumer` to `BiConsumer`? It will provide more flexible approach for notifiers

**Comment by elandau** [comment]
It may be more suitable to pass in the MetricsRegistry instead of relying on logging.  Logging for this will be very noisy and the data would be more easily viewed and analyzed as a data series. 

The MetricsRegistry is already passed into the SimpleLimiter/AbstractLimiter but the limit there is reported as a gauge and not a counter so you wouldn't get every update to the limit.  You could do something similar to what's done with the Gradient2Limit to gain more visibility.

**Comment by IgorPerikov** [comment]
Yeah, thanks for the hint @elandau. I am totally agree with metrics vs logs statement. I am just a bit anxious about introducing limiting for production and looking for a way to reach maximum observability. But you are right - MetricsRegistry abstraction is sufficient for that purpose.

**Pull request closed without merging**
